spring.application.name=password-manager
spring.datasource.url=jdbc:postgresql://db:5432/password_manager
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security & Session Fixes
server.servlet.session.cookie.name=JSESSIONID
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.path=/
server.servlet.session.cookie.same-site=strict
spring.main.allow-bean-definition-overriding=true
logging.level.org.springframework.security=DEBUG
